=== kkrishguptaa/dockyard/api/data.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the program.",
      "type": "string"
    },
    "type": {
      "description": "The type of the program. 'flagship' for flagship programs, 'ysws' for YSWS programs.",
      "type": "string",
      "enum": [
        "flagship",
        "ysws"
      ]
    },
    "draft": {
      "description": "Whether the program is in draft mode. If true, it will not be displayed on the website.",
      "type": "boolean"
    },
    "description": {
      "description": "A brief tagline or description of the program.",
      "type": "string"
    },
    "ys": {
      "description": "The YS (Your Ship) of the program, which is the work or input.",
      "type": "string"
    },
    "ws": {
      "description": "The WS (We Ship) of the program, which is the reward or outcome.",
      "type": "string"
    },
    "extern": {
      "type": "object",
      "properties": {
        "website": {
          "description": "The website link for the program. Can be null if not applicable.",
          "anyOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "null"
            }
          ]
        },
        "slack": {
          "description": "The Slack link and name for the program.",
          "type": "object",
          "properties": {
            "link": {
              "description": "The Slack link for the program. This is the link to the channel.",
              "type": "string",
              "format": "uri"
            },
            "name": {
              "description": "Slack channel name without the # prefix.",
              "type": "string"
            }
          },
          "required": [
            "link",
            "name"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "website",
        "slack"
      ],
      "additionalProperties": false
    },
    "timeline": {
      "description": "The timelines of the program, with start and end dates. Used in a chart to display the timelines of all YSWS.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "start": {
            "type": "string"
          },
          "end": {
            "type": "string"
          }
        },
        "required": [
          "start",
          "end"
        ],
        "additionalProperties": false
      }
    },
    "ships": {
      "description": "An array of ships associated with the program. Each ship has a name, description, URL, and image.",
      "default": [],
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "uri"
          },
          "image": {
            "description": "Will be used in a masonry grid.",
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "name",
          "description",
          "url",
          "image"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "name",
    "type",
    "draft",
    "description",
    "ys",
    "ws",
    "extern",
    "timeline",
    "ships"
  ],
  "additionalProperties": false
}

=== kkrishguptaa/dockyard/api/data/authly.json
{
  "name": "Authly",
  "type": "ysws",
  "draft": true,
  "description": "Build the weirdest auth, get a Security Key",
  "ys": "Weird Auth System for your App",
  "ws": "Security Key",
  "extern": {
    "website": "https://authly.hackclub.com",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C0963JU3CSD",
      "name": "authly"
    }
  },
  "timeline": [
    {
      "start": "2025-07-17T00:00:00-04:00",
      "end": "2025-08-21T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/gamefolio.json
{
  "name": "Gamefolio",
  "type": "ysws",
  "draft": false,
  "description": "You Ship: Make your portfolio site in the style of your favorite game\nWe Ship: $20 grant card which can be spent on either domains or hosting.",
  "ys": "A portfolio site with a game theme",
  "ws": "$20 grant for domains or hosting",
  "extern": {
    "website": "https://gamefolio.hackclub.dev",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C08RT4C2485",
      "name": "gamefolio"
    }
  },
  "timeline": [
    {
      "start": "2025-06-25T00:00:00-04:00",
      "end": "2025-07-15T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/thunder.json
{
  "name": "Thunder",
  "type": "ysws",
  "draft": false,
  "description": "You Ship A Slack bot. We Ship A limited edition Orpheus bucket hat.",
  "ys": "A Slack bot",
  "ws": "A limited edition Orpheus bucket hat",
  "extern": {
    "website": null,
    "slack": {
      "link": "https://hackclub.slack.com/archives/C06V2GEV3MY",
      "name": "thunder"
    }
  },
  "timeline": [
    {
      "start": "2025-05-16T00:00:00-04:00",
      "end": "2025-07-15T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/toolsmith.json
{
  "name": "Toolsmith",
  "type": "ysws",
  "draft": false,
  "description": "Build a AI extension (MCP tool), get $10 of AI credits.",
  "ys": "An MCP tool",
  "ws": "$10 of AI credits",
  "extern": {
    "website": "https://toolsmith.hackclub.com/",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C094X38BFT5",
      "name": "toolsmith"
    }
  },
  "timeline": [
    {
      "start": "2025-07-09T00:00:00-04:00",
      "end": "2025-07-11T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/converge.json
{
  "name": "Converge",
  "type": "ysws",
  "draft": false,
  "description": "Build bots, win prizes",
  "ys": "Discord/Slack/Telegram/Signal Bot",
  "ws": "Multiple Prizes",
  "extern": {
    "website": "https://converge.hackclub.com",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C091UF79VDM",
      "name": "converge"
    }
  },
  "timeline": [
    {
      "start": "2025-06-24T00:00:00-04:00",
      "end": "2025-07-15T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/silicon.json
{
  "name": "Silicon",
  "type": "ysws",
  "draft": false,
  "description": "Design your own custom devboard and we'll fund it.",
  "ys": "Your own custom devboard",
  "ws": "Funding to make it!",
  "extern": {
    "website": "http://silicon.hackclub.dev",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C090WQ9JBTM",
      "name": "silicon"
    }
  },
  "timeline": [
    {
      "start": "2025-06-21T00:00:00-04:00",
      "end": "2025-08-06T23:59:59"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/pulse.json
{
  "name": "Pulse",
  "type": "ysws",
  "draft": false,
  "description": "Build a project using the Spotify API with 6 hours on Hackatime, get 3 months of Spotify Premium.",
  "ys": "A project using the Spotify API",
  "ws": "3 months of Spotify Premium",
  "extern": {
    "website": "https://pulse.hackclub.dev",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C090E7XUEA3",
      "name": "pulse-ysws"
    }
  },
  "timeline": [
    {
      "start": "2025-06-25T00:00:00-04:00",
      "end": "2025-07-11T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/cider.json
{
  "name": "Cider",
  "type": "ysws",
  "draft": false,
  "description": "Create an iOS/MacOS app and receive a $100 Apple Developer account to publish it.",
  "ys": "iOS/MacOS App",
  "ws": "$100 Apple Developer Account",
  "extern": {
    "website": "https://cider.hackclub.com",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C073DTGENJ2",
      "name": "cider"
    }
  },
  "timeline": [
    {
      "start": "2025-05-25T00:00:00-04:00",
      "end": "2025-08-31T23:59:59-04:00"
    }
  ],
  "ships": []
}
