=== kkrishguptaa/dockyard/api/data.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the program.",
      "type": "string"
    },
    "type": {
      "description": "The type of the program. 'flagship' for flagship programs, 'ysws' for YSWS programs.",
      "type": "string",
      "enum": [
        "flagship",
        "ysws"
      ]
    },
    "draft": {
      "description": "Whether the program is in draft mode. If true, it will not be displayed on the website.",
      "type": "boolean"
    },
    "description": {
      "description": "A brief tagline or description of the program.",
      "type": "string"
    },
    "ys": {
      "description": "The YS (Your Ship) of the program, which is the work or input.",
      "type": "string"
    },
    "ws": {
      "description": "The WS (We Ship) of the program, which is the reward or outcome.",
      "type": "string"
    },
    "extern": {
      "type": "object",
      "properties": {
        "website": {
          "description": "The website link for the program. Can be null if not applicable.",
          "anyOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "null"
            }
          ]
        },
        "slack": {
          "description": "The Slack link and name for the program.",
          "type": "object",
          "properties": {
            "link": {
              "description": "The Slack link for the program. This is the link to the channel.",
              "type": "string",
              "format": "uri"
            },
            "name": {
              "description": "Slack channel name without the # prefix.",
              "type": "string"
            }
          },
          "required": [
            "link",
            "name"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "website",
        "slack"
      ],
      "additionalProperties": false
    },
    "timeline": {
      "description": "The timelines of the program, with start and end dates. Used in a chart to display the timelines of all YSWS.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "start": {
            "type": "string"
          },
          "end": {
            "type": "string"
          }
        },
        "required": [
          "start",
          "end"
        ],
        "additionalProperties": false
      }
    },
    "ships": {
      "description": "An array of ships associated with the program. Each ship has a name, description, URL, and image.",
      "default": [],
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "format": "uri"
          },
          "image": {
            "description": "Will be used in a masonry grid.",
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "name",
          "description",
          "url",
          "image"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "name",
    "type",
    "draft",
    "description",
    "ys",
    "ws",
    "extern",
    "timeline",
    "ships"
  ],
  "additionalProperties": false
}

=== kkrishguptaa/dockyard/api/data/dockerize.json
{
  "name": "Dockerize",
  "type": "ysws",
  "draft": false,
  "description": "Build a self-hosted application using Docker, we ship you stickers and a chance to win a ZimaBoard.",
  "ys": "A Dockerized Application",
  "ws": "Stickers and a chance to win a ZimaBoard.",
  "extern": {
    "website": "https://dockerize.hackclub.com/",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C092D9HARSQ",
      "name": "dockerize"
    }
  },
  "timeline": [
    {
      "start": "2025-06-20T00:00:00-04:00",
      "end": "2025-07-11T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/endpointer.json
{
  "name": "Endpointer",
  "type": "ysws",
  "draft": false,
  "description": "Ship a REST API with proper documentation on Swagger (OpenAPI), and we ship a grant for Cloud Credits / Raspberry Pi up to $40",
  "ys": "REST API with documentation",
  "ws": "Cloud Credits / RPI ($40)",
  "extern": {
    "website": "https://endpointer.hackclub.com/",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C097M5JRT7F",
      "name": "endpointer"
    }
  },
  "timeline": [
    {
      "start": "2025-07-30T00:00:00-04:00",
      "end": "2025-08-12T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/terminal-craft.json
{
  "name": "Terminal Craft",
  "type": "ysws",
  "draft": false,
  "description": "Build and publish your own terminal program and earn a $60 grant for hackable electronics!",
  "ys": "Terminal Program",
  "ws": "$60 for RPI/hackable electronics!",
  "extern": {
    "website": "https://terminalcraft.hackclub.com",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C08F58MT3GV",
      "name": "terminal-craft"
    }
  },
  "timeline": [
    {
      "start": "2025-07-14",
      "end": "2025-08-10"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/jet.json
{
  "name": "Jet",
  "type": "flagship",
  "draft": false,
  "description": "Get travel stipends just by programming!",
  "ys": "Tracked Hours of Code",
  "ws": "Travel Stipends!",
  "extern": {
    "website": "https://jet.hackclub.com/",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C09640ENTS7",
      "name": "jet"
    }
  },
  "timeline": [
    {
      "start": "2025-07-17T00:00:00-04:00",
      "end": "2025-08-21T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/cinema.json
{
  "name": "Cinema",
  "type": "ysws",
  "draft": false,
  "description": "Make a short story JavaScript animation using canvas, Get HQ-made caramel popcorn! (card grants for international folks)",
  "ys": "JavaScript Canvas Animation",
  "ws": "Popcorn",
  "extern": {
    "website": "https://cinema.hackclub.com",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C0936AVS683",
      "name": "cinema"
    }
  },
  "timeline": [
    {
      "start": "2025-07-02T00:00:00-04:00",
      "end": "2025-07-07T11:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/illumination.json
{
  "name": "Illumination",
  "type": "ysws",
  "draft": false,
  "description": "Build an IOT device, get everything you need to have it running!",
  "ys": "A program that runs on an ESP32, a backend that connects to your ESP32, and a website to control your ESP32 and backend.",
  "ws": "A cool ESP32-S3 based devboard, hardware parts you choose, and cloud credits to run your backend with.",
  "extern": {
    "website": "https://illumination.hackclub.com",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C091MS57D37",
      "name": "illumination"
    }
  },
  "timeline": [
    {
      "start": "2025-06-25T00:00:00-04:00",
      "end": "2025-07-10T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/dummies.json
{
  "name": "Dummies",
  "type": "ysws",
  "draft": false,
  "description": "Learn A New programming language, and build a project with it and Get a Book",
  "ys": "Learn A New programming language, and build a project with it",
  "ws": "A book of choice from dummies.com",
  "extern": {
    "website": "https://dummies.hackclub.com/",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C096M3EV67M",
      "name": "dummies"
    }
  },
  "timeline": [
    {
      "start": "2025-07-26T00:00:00-04:00",
      "end": "2025-08-14T23:59:59-04:00"
    }
  ],
  "ships": []
}

=== kkrishguptaa/dockyard/api/data/summer-of-making.json
{
  "name": "Summer of Making",
  "type": "flagship",
  "draft": false,
  "description": "Build stuff. Get stuff. Repeat.",
  "ys": "A project of your choice",
  "ws": "Multiple prizes!!!",
  "extern": {
    "website": "http://summer.hackclub.com",
    "slack": {
      "link": "https://hackclub.slack.com/archives/C015M4L9AHW",
      "name": "summer-of-making"
    }
  },
  "timeline": [
    {
      "start": "2025-06-21T00:00:00-04:00",
      "end": "2025-08-31T23:59:59-04:00"
    }
  ],
  "ships": []
}
